import pymongo
db_client = pymongo.MongoClient("mongodb://localhost:27017/")
current_db = db_client["museum"]
collection = current_db["Weapon"]
from PyQt5 import QtCore, QtGui, QtWidgets
from second import Ui_Form
from third import Ui_Form2
from fourth import Ui_Form3
from fifth import Ui_Form4
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(405, 0, 391, 391))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Michail/PycharmProjects/pythonProject2/craiyon_132145_black_and_white_m.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 310, 1180, 200))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 715, 1000, 45))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 600, 200, 75))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 600, 200, 75))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 675, 200, 75))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menuBar)
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu_2.addAction(self.action_1)
        self.menu_2.addAction(self.action_2)
        self.menu_3.addAction(self.action_3)
        self.menu_4.addAction(self.action_4)
        self.menu_5.addAction(self.action_5)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.secondscr)
        self.pushButton_2.clicked.connect(self.fourthscr)
        self.pushButton_3.clicked.connect(self.fifthscr)
        self.action_1.triggered.connect(self.secondscr)
        self.action_2.triggered.connect(self.secondscr)
        self.action_3.triggered.connect(self.fourthscr)
        self.action_4.triggered.connect(self.fifthscr)
        self.action_5.triggered.connect(self.thirdscr)
    def secondscr(self):
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.setStyleSheet("#Form{background-color:white}")
        self.Form.show()
    def thirdscr(self):
        self.Form2 = QtWidgets.QWidget()
        self.ui = Ui_Form2()
        self.ui.setupUi(self.Form2)
        self.Form2.setStyleSheet("#Form{background-color:white}")
        self.Form2.show()
    def fourthscr(self):
        self.Form3 = QtWidgets.QWidget()
        self.ui = Ui_Form3()
        self.ui.setupUi(self.Form3)
        self.Form3.setStyleSheet("#Form{background-color:white}")
        self.Form3.show()
    def fifthscr(self):
        self.Form4 = QtWidgets.QWidget()
        self.ui = Ui_Form4()
        self.ui.setupUi(self.Form4)
        self.Form4.setStyleSheet("#Form{background-color:white}")
        self.Form4.show()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главная страница"))
        self.label_2.setText(_translate("MainWindow", "Императорский Арсенал - музей оружия, представляющий собой захватывающий путешествие в историю боевых искусств и военного прогресса. Внутри его стен посетители могут открыть для себя удивительное разнообразие\n"
                                                      "оружия, которое сыграло важную роль в судьбе человечества. При входе в музей посетителей встречает грандиозный зал, наполненный звуками военных сражений и запахами пороха. Музей разеляет экспонаты по залам,\n"
                                                      "группирую похожие виды орудий."))
        self.label_3.setText(_translate("MainWindow", "Контакты музея:\nЭлектронная почта - abcdifghijklnmopqrstuvwxyz@gmail.com;\nТелефон - +12345678900"))
        self.pushButton.setText(_translate("MainWindow", "Записатся на экскурсию"))
        self.pushButton_2.setText(_translate("MainWindow", "Посмотреть экспонаты"))
        self.pushButton_3.setText(_translate("MainWindow", "Посмотреть расписание"))
        self.menu.setTitle(_translate("MainWindow", "Главная"))
        self.menu_2.setTitle(_translate("MainWindow", "Бронь"))
        self.menu_3.setTitle(_translate("MainWindow", "Экспонаты"))
        self.menu_4.setTitle(_translate("MainWindow", "Экскурсии"))
        self.menu_5.setTitle(_translate("MainWindow", "Настройки"))
        self.action_1.setText(_translate("MainWindow", "Забронировать часную экскурсию"))
        self.action_2.setText(_translate("MainWindow", "Записатся на плановую экскурсию"))
        self.action_3.setText(_translate("MainWindow", "Посмотреть экспонаты"))
        self.action_4.setText(_translate("MainWindow", "Посмотреть расписание"))
        self.action_5.setText(_translate("MainWindow", "Панель администратора"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setStyleSheet("#MainWindow{background-color:white}")
    MainWindow.show()
    sys.exit(app.exec_())